obstacle_range: 2.5
raytrace_range: 3.0
# footprint: [[x0, y0], [x1, y1], ... [xn, yn]]
robot_radius: 0.18
inflation_radius: 0.55

observation_sources: laser_scan_sensor point_cloud_sensor

laser_scan_sensor: {sensor_frame: frame_name, data_type: LaserScan, topic: topic_name, marking: true, clearing: true}

point_cloud_sensor: {sensor_frame: frame_name, data_type: PointCloud, topic: topic_name, marking: true, clearing: true}
obstacle_layer:
  enabled: true
  observation_sources: laser_scan
  laser_scan: {sensor_frame: laser_frame, data_type: LaserScan, topic: scan, marking: true, clearing: true}

inflation_layer:
  enabled: true
  inflation_radius: 0.5  # Adjust this based on your robot's size
