obstacle_range: 2.5
raytrace_range: 3.0
# footprint: [[x0, y0], [x1, y1], ... [xn, yn]]
# robot_radius: 0.18
robot_radius: 0.18
inflation_radius: 0.55

observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: base_link, data_type: LaserScan, topic: scan, marking: true, clearing: true}

obstacle_layer:
  enabled: true
  observation_sources: laser_scan
  laser_scan: {sensor_frame: laser_frame, data_type: LaserScan, topic: scan, marking: true, clearing: true}

inflation_layer:
  enabled: true
  inflation_radius: 0.3  # Adjust this based on your robot's size
