slam_toolbox:
  map_file_name: ""
  resolution: 0.05
  publish_map: true
  map_update_interval: 5.0
  max_laser_range: 10.0
  mode: "mapping"
  optimize_every_n_nodes: 100
  odom_frame: "odom"
  map_frame: "map"
  base_frame: "base_link"
  scan_topic: "/scan"
